ARG REGISTRY=registry.cn-hangzhou.aliyuncs.com
ARG NAMESPACE=sarmn
# OS_TAG     产物标签后缀：base:<OS_TAG> / language:<OS_TAG>-python-3.12 …
# BASE_IMAGE 上游 base 镜像（桌面链为 base:<OS_TAG>-desktop）。Ubuntu 与 openEuler
#            的差异只在这里，安装脚本靠 /etc/os-release 自行分派（见 installer/common.sh）
ARG OS_TAG=noble
ARG BASE_IMAGE=${REGISTRY}/${NAMESPACE}/base:${OS_TAG}
FROM ${BASE_IMAGE} as builder

ARG REDIS_PIN_VERSION

COPY ./docker_installer/installer/common.sh /deployment/scripts/common.sh
COPY ./docker_installer/installer/middleware/redis/install_redis.7.4.sh /tmp/install_redis.sh
# --secret id=REDIS_PASSWORD,env=REDIS_PASSWORD
RUN --mount=type=secret,id=REDIS_PASSWORD,required=false \
    set -eux; \
    [ -s /run/secrets/REDIS_PASSWORD ] && export REDIS_PASSWORD="$(cat /run/secrets/REDIS_PASSWORD)"; \
    /bin/bash /tmp/install_redis.sh

FROM ${BASE_IMAGE}
COPY --from=builder /deployment/software/redis /deployment/software/redis
COPY --from=builder /etc/s6-overlay/s6-rc.d/redis /etc/s6-overlay/s6-rc.d/redis
COPY --from=builder /etc/s6-overlay/s6-rc.d/user/contents.d/redis /etc/s6-overlay/s6-rc.d/user/contents.d/redis
COPY --from=builder /etc/cont-env.d/REDIS_VERSION /etc/cont-env.d/REDIS_VERSION
COPY --from=builder /etc/cont-env.d/REDIS_SERIES /etc/cont-env.d/REDIS_SERIES
COPY --from=builder /etc/environment /etc/environments/env-redis

ENV PATH=/deployment/bin:/deployment/software/redis/bin:$PATH \
    REDIS_SERIES=7.4

RUN ln -s /deployment/software/redis/bin/redis-server /deployment/bin/redis-server ;\
    ln -s /deployment/software/redis/bin/redis-cli /deployment/bin/redis-cli ;\
    /bin/bash -c "source /deployment/scripts/common.sh && merge_and_save_env"

EXPOSE 6379
ENTRYPOINT ["/init"]
