FROM ubuntu:noble
LABEL authors="sarmn"

ENV PATH=/deployment/bin:$PATH
ENV LANG zh_CN.UTF-8
ENV LANGUAGE zh_CN:zh
ENV LC_ALL zh_CN.UTF-8
COPY ./docker_installer/installer/common.sh /deployment/scripts/common.sh
COPY ./docker_installer/installer/base/install_base.sh /deployment/scripts/install_base.sh
RUN /bin/bash /deployment/scripts/install_base.sh ;\
    echo 'source /deployment/scripts/common.sh' >> /etc/bash.bashrc ;\
    touch /etc/s6-overlay/s6-rc.d/user/contents.d/sshd

ENTRYPOINT ["/init"]
